### ISSUE TITLE
cp6_eval.py crashing on output from `run.sh`

### ISSUE THREAD

**Issue by mhuesch** [GaloisInc/ppaml-cp6#9]
Hi,

I have done a full run through the round-1-public sandbox using the `run.sh` script. When I run `eval.sh` (from the `config_commit` branch - https://github.com/GaloisInc/ppaml-cp6/blob/config_commit/data_preparation_tools/eval.sh) on it, though, it gives this error:

```
Info: read 24 labels
Info: read 2000 answer-key entries
Traceback (most recent call last):
  File "/home/peval/git/ppaml-cp6/data_preparation_tools/tools/cp6_eval.py", line 123, in <module>
    computed_it = ImageTable.read_from_file( args.ct )
  File "/home/peval/git/ppaml-cp6/data_preparation_tools/cp6/tables/image_table.py", line 100, in read_from_file
    raise AssertionError( 'Image table %s:%d: found %d fields, expecting 10' % (fn, c, len(fields)))
AssertionError: Image table run_out//testing/classified_labels.txt:1: found 4 fields, expecting 10
```

I am a bit mystified because I also have a run from the `toy-sandbox` and that one can successfully be evaluated. The file implicated by the AssertionError (classified_labels.txt) appears to be in the same format of 3 space-separated tokens per line in both files.

I've tarred up the output from the two runs here: [toy_output.tar.bz2](https://owncloud.galois.com/public.php?service=files&t=d9da159ebce924c50c35e1b3fd5b440c) & [round-1-public_output.tar.bz2](https://owncloud.galois.com/public.php?service=files&t=c2869eeef1da45d0e046bb828c467a8c). The command I ran were:
```
$ ~/git/ppaml-cp6/data_preparation_tools/eval.sh run_out eval_in /tmp/eval_big_run
```
and
```
$ ~/git/ppaml-cp6/data_preparation_tools/eval.sh run_out eval_in /tmp/eval_toy_run
```
The output goes to the third argument directory, in the file `eval.log`.

If you guys could take a look it would be much appreciated! Thanks.

**Comment by collinsr** [comment]
> AssertionError: Image table run_out//testing/classified_labels.txt:1: found 4 fields, expecting 10

This means that classified_labels.txt is not a well-formed image_table. Upon inspection, it only generates output for two classes, but there are 24 labels defined. The system has no way of knowing which classes the two probabilities are meant to map to.

As background, the original specification called for teams to submit for scoring an exact copy of the input image table, but with all the "-2" (=="guess this label") values filled in with the likelihood estimates.  These files have 10 space-separated fields (hence the "expecting 10" message); the last one is a comma-separated string. Each value in this string maps to the corresponding entry in the label_table. So if you have 24 classes in the label_table, this string would have 24 comma-separated values.

After I wrote up the scoring code, Eran pointed out that reconstructing this table might not always be convenient. So the scoring code accepts an alternate format: one response per line, each line has the format

image_id  class_estimate_1 class_estimate_2 ... class_estimate_N

...where, in this case, N == 24. The scoring code looks at the first line to guess which format is being used. If the first line has N+1 space-separated values, it assumes its the second "reduced" format. Otherwise, it attempts to load the file as a fully populated image_table. (This breaks if nLabels == 9 and you try to score a fully-populated image_table; I'll make the guessing more robust.)

So back to this problem. classified_labels.txt has the format

image_id class_estimate_1 class_estimate_2

...which would would work if the number of labels == 2, but it doesn't ("Info: read 24 labels"), so it tries to read it as an image table, and fails. It works for the toy example because there nLabels does == 2. 

I assume this is running Eran's CRF code? I'm tagging him in so he can check it out-- @eswears, does Michael's config only compute labels for two classes? If so, we still need to output a full zero-padded 24-column vector of estimates so the scoring code can line them up with the correct truth class ID.

**Comment by mhuesch** [comment]
Ah - I have figured it out. I was playing with the configurations trying to do partial runs (so they would go faster) and then forgot to reset the values. Sorry for the noise, and thanks for your response!

**Comment by eswears** [comment]
The config file has a new parameter that you might have noticed “data_type”.  By default it is set to ‘sandbox’, but you may have changed it to ‘demo’ to run the “toy-sandbox” data. Was it set to ‘sandbox’ when you ran the “round-1-public sandbox”?

 

We have slightly different internal names for the data, which may be causing some confusion. I’ll clarify this in the next version of the config file and readme.

 

-Eran

**Comment by eswears** [comment]
No, problem. I have this same problem from time to time…

 

I just replied to your previous e-mail, no need to respond now.  

 

-Eran
